export const PROJECTS = [
  {
    name: "JCommerce",
    image: "jcommerce1.png",
    projectType: "Next.js",
    url: "jcommerce",
    type: "Full Stack Application",
    technologies: [
      "React",
      "Next.js",
      "Typescript",
      "Tailwind CSS",
      "MongoDB",
      "NextAuth",
      "Google Cloud Console",
      "Stripe",
      "AWS",
    ],
  },
  {
    name: "Google Jocs",
    image: "googlejocs1.png",
    projectType: "Next.js",
    url: "google-jocs",
    type: "Full Stack Application",
    technologies: [
      "React",
      "Next.js",
      "Typescript",
      "Tailwind CSS",
      'Material UI',
      "Firebase",
      "NextAuth",
    ],
  },
  {
    name: "Campr",
    image: "campr.png",
    projectType: "Next.js",
    url: "campr",
    type: "Frontend UI",
    technologies: ["React", "Next.js", "Typescript", "Tailwind CSS"],
  },
];
